version: "3.3"

services:
  api:
    container_name: node_efishery_backend_test
    build: .
    env_file: .env
    ports:
      - 8000:8000
    command: "npm run start"
    volumes:
      - ./public:/home/restify/efishery-backend-test/public
